test(deploy): add debug files

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,9 +39,10 @@ jobs:
     steps:
       - name: Debug files
         run: |
+          echo "ROOT:"
           ls -R .
           echo "Check specific file:"
-          ls -l deploy/prod/
+          ls -l deploy/prod/ || echo "Directory deploy/prod/ NOT FOUND"
       - name: Copy required files
         uses: appleboy/scp-action@v1
         with:
@@ -49,7 +50,7 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           source: deploy/prod/docker-compose.yaml
-          target: ~/app/docker-compose.yaml
+          target: ~/app/
 
       - name: VPS Deploy
         uses: appleboy/ssh-action@v1.2.0
